services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    volumes:
      - '~/volumes/e-backend/postgres:/var/lib/postgresql/data'