spring:
    flyway:
        enabled: true
        url: jdbc:postgresql://localhost:5432/postgres
        user: postgres
        password: 123456
    r2dbc:
        url: r2dbc:postgresql://localhost:5432/postgres
        username: postgres
        password: 123456
    security:
        user:
            name: admin
            password: admin123
jwt:
    secret: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration: 3600