spring:
    flyway:
        enabled: true
        url: jdbc:postgresql://localhost:5432/postgres
        user: postgres
        password: 123456
    r2dbc:
        url: r2dbc:postgresql://localhost:5432/postgres
        username: postgres
        password: 123456