spring:
    flyway:
        enabled: true
        url: jdbc:postgresql://localhost:5432/postgres
        user: postgres
        password: 123456
    r2dbc:
        url: r2dbc:postgresql://localhost:5432/postgres
        username: postgres
        password: 123456
    config:
        import: optional:file:.env[.properties]

jwt:
    secret: ${SECRET_KEY}
    expiration: ${EXPIRATION_TIME}

cloudinary:
    cloudName: ${CLOUD_NAME}
    apiKey: ${API_KEY}
    apiSecret: ${API_SECRET}